apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: multi-tenant-crm
  labels:
    app: multi-tenant-crm
    component: backend
    managed-by: kubernetes
  annotations:
    secret.kubernetes.io/rotation-schedule: "30d"
    secret.kubernetes.io/last-rotated: "2024-01-01T00:00:00Z"
    secret.kubernetes.io/managed-by: "kubernetes"
    secret.kubernetes.io/compliance-level: "high"
    secret.kubernetes.io/backup-enabled: "true"
    secret.kubernetes.io/encryption-provider: "aws-kms"
    secret.kubernetes.io/kms-key-id: "${AWS_KMS_KEY_ID}"
type: Opaque
data:
  # JWT Authentication Secrets (from auth.config.ts)
  JWT_ACCESS_SECRET: "${base64_encoded_jwt_access_secret}"
  JWT_REFRESH_SECRET: "${base64_encoded_jwt_refresh_secret}"
  JWT_ALGORITHM: "SFMyNTY=" # Base64 encoded "HS256"
  JWT_ISSUER: "bXVsdGktdGVuYW50LWNybQ==" # Base64 encoded "multi-tenant-crm"

  # MongoDB Connection Settings (from database.config.ts)
  MONGODB_URI: "${base64_encoded_mongodb_uri}"
  MONGODB_MAX_POOL_SIZE: "MTAw" # Base64 encoded "100"
  MONGODB_SSL_ENABLED: "dHJ1ZQ==" # Base64 encoded "true"
  MONGODB_REPLICA_SET: "${base64_encoded_replica_set}"

  # SMTP Configuration (from email.config.ts)
  SMTP_HOST: "${base64_encoded_smtp_host}"
  SMTP_PORT: "NTg3" # Base64 encoded "587"
  SMTP_SECURE: "dHJ1ZQ==" # Base64 encoded "true"
  SMTP_USER: "${base64_encoded_smtp_user}"
  SMTP_PASS: "${base64_encoded_smtp_pass}"
  EMAIL_FROM: "${base64_encoded_email_from}"
  EMAIL_REPLY_TO: "${base64_encoded_email_reply_to}"
  EMAIL_TEMPLATE_DIR: "${base64_encoded_template_dir}"

  # AWS Storage Configuration (from storage.config.ts)
  AWS_REGION: "${base64_encoded_aws_region}"
  AWS_BUCKET_NAME: "${base64_encoded_bucket_name}"
  AWS_ACCESS_KEY_ID: "${base64_encoded_aws_access_key}"
  AWS_SECRET_ACCESS_KEY: "${base64_encoded_aws_secret_key}"
  AWS_KMS_KEY_ID: "${base64_encoded_kms_key_id}"
  AWS_ENDPOINT_URL: "${base64_encoded_endpoint_url}"

  # Cookie Security Settings (from auth.config.ts)
  COOKIE_DOMAIN: "${base64_encoded_cookie_domain}"
  COOKIE_SECURE: "dHJ1ZQ==" # Base64 encoded "true"
  COOKIE_SAME_SITE: "c3RyaWN0" # Base64 encoded "strict"